language: ruby

before_install:
  - gem install bundler -v '<2'

bundler_args: --without development --jobs=3 --retry=3

sudo: false

rvm:
  - 2.4.9
  - 2.5.3
  - 2.6.1
  - jruby-9.2.6.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
